### ISSUE TITLE
Scale  looks funny for k=0.75

### ISSUE THREAD

**Issue by groceryheist** [bearloga/tinydensR#5]
Compared to `rweibull` the plot by tidydensR doesn't look quite right. The shape of the density looks pretty good, but the range of the Y axis is really high! This is probably because when k < 1 the density has a vertical asymptote at 0. I don't really know what you want to do about this, but maybe a partial solution could be keeping the Y axis fixed for all parameter values.

![image](https://user-images.githubusercontent.com/113311/46845084-b7f2e880-cd8e-11e8-8f9d-ac0cf6902b1d.png)

**Comment by bearloga** [comment]
I've been thinking about adding more customization options and I think this is a good enough reason for user-specified ylim. Maybe xlim too. I'll try adding that and we can see if it works.

**Comment by bearloga** [comment]
@groceryheist please let me know how you like the new options
